### ISSUE TITLE
`stosd` not highlighted as a command

### ISSUE THREAD

**Issue by thepulkitagarwal** [MakiseKurisu/MasmAssembly#6]
in ST2, `stosd` isn't highlighted, but `stosw` and `stosb` are.

Thank you!

**Comment by MakiseKurisu** [comment]
Thanks.

**Comment by thepulkitagarwal** [comment]
![stos](https://cloud.githubusercontent.com/assets/6085092/13545495/faefe55c-e2b3-11e5-940c-6b53fc1c267e.png)
I think there's another problem now, as you can see in the image.. Can you check if that is the case?
