### ISSUE TITLE
Problem with `stosb/stosw/stosd` highlighting

### ISSUE THREAD

**Issue by thepulkitagarwal** [MakiseKurisu/MasmAssembly#7]
![stos](https://cloud.githubusercontent.com/assets/6085092/13545495/faefe55c-e2b3-11e5-940c-6b53fc1c267e.png)
I think there's another problem now, as you can see in the image.. Can you check if that is the case?

**Comment by MakiseKurisu** [comment]
Please check if everything is fine now. Sorry I don't use ST anymore nor do I write assembly on a regular basis.

**Comment by thepulkitagarwal** [comment]
Everything works great! And Thank you for helping me out!
