### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by Alexey-T** [MakiseKurisu/MasmAssembly#8]
Can you upload sample folder: samples for 2 Asm modes, to test?

**Comment by MakiseKurisu** [comment]
What do you mean by "asm mode"?

If you are talking about some sample assembly code, than this is not a tutorial about how to write assembly. If you don't have the assembly code ready why you want to install this syntax highlighting plugin?

**Comment by Alexey-T** [comment]
I mean sample assembler files. for 2 modes. JWAsm, Masm. to see how full the syntax sopport is.

**Comment by MakiseKurisu** [comment]
It does not provide full support as stated in the README.md. I only include the most common thing here to get my job done and I will add rare keyword when there is an issue for it.
